/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteDetail"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StopInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stops/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    lat: number;
                    lon: number;
                    radius?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NearbyStop"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    fromLat: number;
                    fromLon: number;
                    toLat: number;
                    toLon: number;
                    departAt?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Journey"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        Journey: {
            /** Format: date-time */
            departure: string;
            /** Format: date-time */
            arrival: string;
            /** Format: int32 */
            transfers: number;
            legs: components["schemas"]["JourneyLeg"][];
        };
        JourneyLeg: {
            mode: components["schemas"]["LegMode"];
            from: components["schemas"]["LegPlace"];
            to: components["schemas"]["LegPlace"];
            /** Format: date-time */
            departure: string;
            /** Format: date-time */
            arrival: string;
            /** Format: int32 */
            distanceMeters: number;
            routeId?: null | string;
            routeShortName?: null | string;
            routeColor?: null | string;
            headsign?: null | string;
            /** Format: int32 */
            stopCount?: null | number;
            /** @default false */
            approximate: boolean;
            stops?: null | components["schemas"]["LegPlace"][];
        };
        /** @enum {unknown} */
        LegMode: "Walk" | "Transit";
        LegPlace: {
            stopId: null | string;
            name: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
        NearbyStop: {
            id: string;
            code: null | string;
            name: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            /** Format: int32 */
            distanceMeters: number;
        };
        RouteDetail: {
            id: string;
            shortName: string;
            longName: string;
            type: components["schemas"]["RouteType"];
            color: null | string;
            agencyName: string;
            directions: components["schemas"]["RouteDirection"][];
        };
        RouteDirection: {
            /** Format: int32 */
            directionId: number;
            headsign: null | string;
            stops: components["schemas"]["StopInfo"][];
        };
        RouteSummary: {
            id: string;
            shortName: string;
            longName: string;
            type: components["schemas"]["RouteType"];
            color: null | string;
        };
        /** @enum {unknown} */
        RouteType: "Tram" | "Subway" | "Rail" | "Bus";
        StopInfo: {
            id: string;
            code: null | string;
            name: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
